// import "./src/components/motorCycleComponent/index.scss";
// import "./src/components/headerComponent/index.scss";
// import "./src/components/headerComponent/index.scss";
// import "./src/components/buttonComponent/index.scss";
// import "./src/components/headerComponent/index.scss";
// import "./src/components/heroBannerComponent/index";
// import "./src/components/mapComponent/index.scss";

// import { whyTonrowGenerator } from "./src/components/whyTonrowComponent/whyTonrowComponent";
// import renderBreakMotor from "./src/components/motorCycleComponent/motorCycleComponent";
// import baseButtonGenerator from "./src/components/buttonComponent/buttonComponent";
// import buttonOptions from "./src/components/buttonComponent/configButtonComponent";
// import generatorDOMWhatDoesTonrowDo from "./src/components/whatDoesTonrowDo/index";
// import brandIconGenerator from "./src/components/brandTrust/brandTrustComponent";
// import renderMap from "./src/components/mapComponent/mapComponent";

// Define the default role
// heroBannerSection()
// renderBreakMotor()






// const defaultRole = "public";


// const defaultRole = "safir";
// renderMap()


// const customButton = baseButtonGenerator(buttonOptions);
// document.body.appendChild(customButton);

// const defaultRole = "safir";
//! Testing
// const buttonOptions = {
//   content: "My Button",
//   size: "large",
//   type: "button",
//   attributes: {
//     class: "btn-primary",
//   },
//   dataattributes: {
//     main: "primer",
//   },
// };
// button
//! Testing
// const customButton = baseButtonGenerator(buttonOptions);
// document.body.appendChild(customButton);
//***************************************** */
// generatorDOMWhatDoesTonrowDo();

// heroBannerSection()

// HEADER IMPORTS (DO NOT EDIT THIS FILES!)
// import header from "./src/components/headerComponent/headerComponent";
// import "./src/components/headerComponent/index.scss";
// import { getHeaderDataByRole } from "./src/components/headerComponent/validate";
// import handleHeaderError from "./src/components/headerComponent/errorHandler"; 
// const defaultRole = "safir";
// const headerData = getHeaderDataByRole(defaultRole);
// handleHeaderError(headerData);