// import "./src/components/heroBannerComponent/index";
// import "./src/components/mapComponent/index.scss";

// import { whyTonrowGenerator } from "./src/components/whyTonrowComponent/whyTonrowComponent";
// import baseButtonGenerator from "./src/components/buttonComponent/buttonComponent";
// import buttonOptions from "./src/components/buttonComponent/configButtonComponent";
// import brandIconGenerator from "./src/components/brandTrust/brandTrustComponent";
// import renderMap from "./src/components/mapComponent/mapComponent";

// import generatorDOMWhatDoesTonrowDo from "./src/components/whatDoesTonrowDo/index";

// Define the default role

// const defaultRole = "public";

// const customButton = baseButtonGenerator(buttonOptions);
// document.body.appendChild(customButton);

// const customButton = baseButtonGenerator(buttonOptions);
// document.body.appendChild(customButton);
// generatorDOMWhatDoesTonrowDo();

// HEADER IMPORTS (DO NOT EDIT THIS FILES!)
// import header from "./src/components/headerComponent/headerComponent";
// import "./src/components/headerComponent/index.scss";
// import { getHeaderDataByRole } from "./src/components/headerComponent/validate";
// import handleHeaderError from "./src/components/headerComponent/errorHandler";
// const defaultRole = "safir";
// const headerData = getHeaderDataByRole(defaultRole);
// handleHeaderError(headerData);
