// import "./src/components/motorCycleComponent/index.scss";
// import "./src/components/heroBannerComponent/index";
// import "./src/components/mapComponent/index.scss";

// import { whyTonrowGenerator } from "./src/components/whyTonrowComponent/whyTonrowComponent";
// import renderBreakMotor from "./src/components/motorCycleComponent/motorCycleComponent";
// import baseButtonGenerator from "./src/components/buttonComponent/buttonComponent";
// import generatorDOMWhatDoesTonrowDo from "./src/components/whatDoesTonrowDo/index";
// import buttonOptions from "./src/components/buttonComponent/configButtonComponent";
// import brandIconGenerator from "./src/components/brandTrust/brandTrustComponent";
// import { getHeaderDataByRole } from "./src/components/headerComponent/validate";
// import rowGenerator from "./src/components/footerComponent/footerComponent";
// import header from "./src/components/headerComponent/headerComponent";
// import renderMap from "./src/components/mapComponent/mapComponent";

// const defaultRole = "safir";


// Define the default role
// heroBannerSection()
// renderBreakMotor()

// renderMap()

// const customButton = baseButtonGenerator(buttonOptions);
// document.body.appendChild(customButton);

// const defaultRole = "safir";
//! Testing
/**========================================================================
 * todo                             BUTTON
 *   The style of each button is imported to the page as an object. 
 *   And it can be added to the page as two lines below.
 *   
 *
 *========================================================================**/ 

// const customButton = baseButtonGenerator(buttonOptions);
// document.body.appendChild(customButton);
//! Testing


// generatorDOMWhatDoesTonrowDo();

// heroBannerSection()

// HEADER IMPORTS (DO NOT EDIT THIS FILES!)
// import header from "./src/components/headerComponent/headerComponent";
// import "./src/components/headerComponent/index.scss";
// import { getHeaderDataByRole } from "./src/components/headerComponent/validate";
// import handleHeaderError from "./src/components/headerComponent/errorHandler";
// const defaultRole = "user";
// const headerData = getHeaderDataByRole(defaultRole);
// handleHeaderError(headerData);
